# Set theme
remote_theme: daviddarnes/alembic
#remote_theme: alembic-jekyll-theme
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://blog.sout.vip/'
baseurl: ''
title: 'A Simple Programmer'
description: 'This is my new website'
permalink: /:title
logo: "/assets/logos/logo.svg"

url: https://sout.vip/

# Pagination
paginate: 8
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /

# Footer nav
navigation_footer:
  TOP: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My Thoughts and Ideas"
    feature_text: |
      My Thoughts and Ideas
    feature_image: "https://picsum.photos/2560/600?image=866"
